Parameters:
  # Parameter for specifying the name of an existing EC2 key pair
  newKeyPairNameParameter:
    Type: String
    Description:          # Enter a description for the Key Pair parameter
    Default:              # Set a default value for the Key Pair parameter

Resources:
  # Create a new Key Pair
  InstanceKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName:
        Ref:              # Reference the KeyName associated with the Key Pair parameter

  # EC2 Instance
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName:
        Ref:              # Reference the KeyName associated with the Key Pair parameter
