# Security Group
InstanceSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription:      # Enter a description for the security group
    GroupName:             # Enter a name for the security group
    SecurityGroupIngress:  # Define inbound rules for the security group
      - IpProtocol: tcp
        FromPort: 22       # SSH
        ToPort: 22
        CidrIp:            # Enter the CIDR IP range for SSH access
      - IpProtocol: tcp
        FromPort: 80       # HTTP
        ToPort: 80
        CidrIp:            # Enter the CIDR IP range for HTTP access
      - IpProtocol: tcp
        FromPort: 443      # HTTPS
        ToPort: 443
        CidrIp:            # Enter the CIDR IP range for HTTPS access
    Tags:
      - Key: Name
        Value:             # Enter a name for the security group (if needed)
